name: image_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # You can specify your desired Python version
  - numpy
  - opencv
  - ros-rosbag
  - pillow  # Optional, for image processing if needed
  - ros-cv-bridge  # Install cv-bridge from the conda-forge channel

