name: image_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # You can specify your desired Python version
  #- opencv
  - ros-rosbag
  #- ros-cv-bridge  # Install cv-bridge from the conda-forge channel

